Inconsistent darwin/mac_os_x symbol bug It was causing: lib/qt/qmake.rb:114:in `check_qmake!': undefined method `strip' for nil:NilClass (NoMethodError)